### ISSUE TITLE
Remove state file on shutdown?

### ISSUE THREAD

**Issue by jmeisele** [aws-samples/sagemaker-studio-apps-lifecycle-config-examples#1]
Ran into a situation where I tried to re-launch a space after the idle checker shutdown the app. Because the state file already existed the LCC kept triggering SIGTERM before the app could even get started. Should we remove the state file on shutdown to start fresh on every launch?

**Comment by giuseppeporcelli** [comment]
Hi @jmeisele thanks for reporting this issue. We'll further investigate this behavior and keep the issue posted.

**Comment by giuseppeporcelli** [comment]
Thanks for your patience. The state file does not need to be removed on shutdown, because it is stored under `/var/tmp` that is not persisted across restarts (unless you explicitly changed its location).

To further investigate your issue, could you please share the logs available in Amazon CloudWatch in the log group named `/aws/sagemaker/studio` and log streams named `<domain_id>/<space_name>/JupyterLab/default` and `<domain_id>/<space_name>/JupyterLab/default/LifecycleConfigOnStart` ?

Thank you.

**Comment by jmeisele** [comment]
I can't replicate the error and testing works great, closing out the issue 👍🏻
